; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-devkitm-1]
platform = espressif32
board = esp32-s3-devkitm-1
framework = arduino
upload_speed = 921600
monitor_speed = 115200
board_build.partitions = partitions_ota.csv
lib_deps =
	fastled/FastLED @ ^3.9.12
	adafruit/Adafruit NeoPixel @ ^1.12.3
build_flags =
	-DAPP_VERSION=\"0.1.8\"
	-DLED_DATA_PIN=18
	-DLED_STRIP_LENGTH=1600
	-DSTATUS_LED_FORCE_MONO=1
	-DDEBUG_EFFECTS_RUN_ON_MAIN_LOOP=1
	-DDEBUG_EFFECTS_OUTPUT_MAX=256
	-DDEBUG_DISABLE_EFFECTS_INIT=0
	-DDEBUG_DISABLE_EFFECTS_TICK=0
	-DDEBUG_DISABLE_OTA_RUNTIME=0
