; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-devkitm-1]
platform = espressif32
board = esp32-s3-devkitm-1
framework = arduino
upload_speed = 921600
monitor_speed = 115200
board_build.partitions = partitions_ota.csv
lib_deps =
	fastled/FastLED @ ^3.9.12
	makuna/NeoPixelBus @ ^2.8.0
build_flags =
	-DAPP_VERSION=\"0.1.10\"
	-DLED_DATA_PIN=18
	-DLED_STRIP_LENGTH=1600
	-DLED_TRANSPORT_USE_BITBANG=0
	-DEFFECTS_ENABLE_REGISTRATION=1
build_src_filter =
	+<*>
